#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.21.22:3306/jufan_crawler?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: We-are-hero-2015
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool
      read-only: false
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
mybatis-plus:
  global-config:
    $symbol_pound xml调试,无需重启
    refresh: true
jetcache:
  statIntervalMinutes: 15
  hidePackages: ${package}
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 100
      expireAfterWriteInMillis: 30000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      expireAfterWriteInMillis: 100000
      uri: redis://We-are-hero-2015@192.168.21.27?database=0
      keyPrefix: '${artifactId}:'